steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "frontend/Dockerfile"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/textzy/textzy-frontend:$COMMIT_SHA"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/textzy/textzy-frontend:latest"
      - "frontend"

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/textzy/textzy-frontend:$COMMIT_SHA"
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/textzy/textzy-frontend:latest"

options:
  logging: CLOUD_LOGGING_ONLY
